apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  - name: toleration-app
    key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"